lago-835 stables
BlindexDAO/BlinDEX pull request #169
Opened 2022-05-20 16:31 UTC by AndrzejGisWideLab

## What's the purpose of your PR?

- [ ] Fixing a bug
- [ ] A new Feature
- [ ] Techdebt
- [ ] General Task

## What is your PR all about?

## Any special instructions for the reviewer?

2022-06-02 11:01 UTC, kazazor commented
@AndrzejGisWideLab I see there areerge conflicts in the PR, let's fix them so we could ahve the complete version of it

2022-06-02 12:17 UTC, AndrzejGisWideLab commented
@kazazor sorry, done

2022-06-06 09:38 UTC, tkeidar requested changes
🤙 looks good

I've completed reviewing the code and had several comments - nothing critical

2022-06-06 09:38 UTC, tkeidar commented on tasks/staking.ts
> +      await recorder.execute();
NIT
we can move the execute() to be inside the if statement as it will execute nothing in case the staking pool is already paused

2022-06-06 09:38 UTC, tkeidar commented on tasks/staking.ts
> +      await recorder.execute();
same here

2022-06-06 09:38 UTC, tkeidar commented on tasks/staking.ts
> +      const stikingRecordable = toRc(staking, recorder);
stikingRecordable => stakingRecordable

2022-06-06 09:38 UTC, tkeidar commented on tasks/staking.ts
> +      const stikingRecordable = toRc(staking, recorder);
or maybe a better name will be `recordableStakingReward`
NIT - leaving it up to you to decide

2022-06-06 09:38 UTC, tkeidar commented on tasks/staking.ts
> +      await stakingRewardsDistribution.record.collectAllRewards(0, numberOfStakingPools - 1);
```suggestion
      await stakingRewardsDistribution.record.collectAllRewards(0, 100);
```

we have a known bug here causing the same stakingPool to be added to the list more than once

2022-06-06 09:38 UTC, tkeidar commented on tasks/users.ts
> +    const contracts = await getContractsToTransferOwnership(hre);
nice 👏

2022-06-06 09:38 UTC, tkeidar commented on tasks/users.ts
> +    const recorder = await defaultTimelockRecorder(hre, { executionStartInDays: null, singer: proposer });
```suggestion
    const recorder = await defaultTimelockRecorder(hre, { executionStartInDays: null, signer: proposer });
```

I see this typo in more other places so you better find & replace all of them

2022-06-06 09:38 UTC, tkeidar commented on tasks/users.ts
> +      await toRc(contract, recorder).record.transferOwnership(deployer.address);
let's add a log before every execution so it will be easier to trace this task

2022-06-06 09:38 UTC, tkeidar commented on tasks/users.ts
> +        const contractRecordable = toRc(contract, recorder);
let's add a log on every `setUpdater` execution

2022-06-06 09:38 UTC, tkeidar commented on tasks/users.ts
> +          await contractRecordable.record.setTreasury(treasury);
add a log before calling `setTreasury`

2022-06-06 09:38 UTC, tkeidar commented on utils/DeployedContractsHelpers.ts
> +  return [await getBdUs(hre), await getBdEu(hre), await getBxau(hre), await getBgbp(hre)];
NIT - you better use Promise.all here

2022-06-06 09:38 UTC, tkeidar commented on utils/DeployedContractsHelpers.ts
> +export async function getBlindexUpdater(hre: HardhatRuntimeEnvironment, signer: Signer | undefined): Promise<BlindexUpdater> {
NIT
```suggestion
export async function getBlindexUpdater(hre: HardhatRuntimeEnvironment, signer?: Signer): Promise<BlindexUpdater> {
```

2022-06-06 09:38 UTC, tkeidar commented on utils/Recorder/Recorder.ts
> +export async function defaultRecorder(hre: HardhatRuntimeEnvironment, params: DefaultRecorderParams | undefined = undefined) {
NIT
```suggestion
export async function defaultRecorder(hre: HardhatRuntimeEnvironment, params?: DefaultRecorderParams) {
```

2022-06-06 09:38 UTC, tkeidar commented on utils/Recorder/Recorder.ts
> +export async function defaultTimelockRecorder(hre: HardhatRuntimeEnvironment, params: DefaultRecorderParams | undefined = undefined) {
```suggestion
export async function defaultTimelockRecorder(hre: HardhatRuntimeEnvironment, params?: DefaultRecorderParams) {
```

2022-06-07 12:48 UTC, tkeidar commented on tasks/staking.ts
> +      const stikingRecordable = toRc(staking, recorder);
```suggestion
      const stakingRecordable = toRc(staking, recorder);
```

2022-06-07 13:14 UTC, AndrzejGisWideLab commented on tasks/staking.ts
> +      if (await stikingRecordable.paused()) {
```suggestion
      if (await stakingRecordable.paused()) {
```

2022-06-07 13:14 UTC, AndrzejGisWideLab commented on tasks/staking.ts
> +        await stikingRecordable.record.unpause();
```suggestion
        await stakingRecordable.record.unpause();
```

2022-06-07 13:14 UTC, AndrzejGisWideLab commented on tasks/staking.ts
> +        console.log("already unpaused", stikingRecordable.address);
```suggestion
        console.log("already unpaused", stakingRecordable.address);
```

2022-06-12 07:25 UTC, tkeidar approved these changes

2022-06-12 07:25 UTC, merged